Presentation/IQDashboard.Web/Models/ErrorViewModel.cs
using System;

namespace IQDashboard.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Presentation/IQDashboard.Web/Models/ProjectSummaryModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace IQDashboard.Web.Models
{
    public class ProjectSummaryModel
    {
        [Required(ErrorMessage = "Please enter client name.")]
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string ClientName { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string ProjectName { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string Function { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string BUHead { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string DeliveryHead { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string AccountManager { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string ProjectManager { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string CurrentSOW { get; set; }
        public DateTime ProjectStartDate { get; set; }
        public DateTime ProjectEndDate { get; set; }
        public DateTime ActualStartDate { get; set; }
        public DateTime ForecastedEndDate { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string ProjectType { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string PricingCode { get; set; }
        [MaxLength(50, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string BillingType { get; set; }

        [MaxLength(500, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string ProjectSummary { get; set; }
        [MaxLength(500, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string PSC { get; set; }
        [MaxLength(500, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string Assumptions { get; set; }
        [MaxLength(500, ErrorMessage = "You have reached your maximum limit of characters allowed.")]
        public string Constraints { get; set; }
    }
}

Presentation/IQDashboard.Web/Models/TopMenuModel.cs
using System.Collections.Generic;

namespace IQDashboard.Web.Models
{
    public class TopMenuModel
    {
        public IList<VerticalModel> verticals { get; set; }
    }
}

Presentation/IQDashboard.Web/Models/VerticalModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IQDashboard.Web.Models
{
    public class VerticalModel
    {
        public int VerticalId { get; set; }
        public string Vertical { get; set; }
        public bool IsActive { get; set; }
        public int? NavId { get; set; }
    }
}

Presentation/IQDashboard.Web/Components/MenuViewComponent.cs
using IQDashboard.Web.Factories;
using Microsoft.AspNetCore.Mvc;

namespace IQDashboard.Web.Components
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly IIQModelFactory _projectModelFactory;

        public MenuViewComponent(IIQModelFactory projectModelFactory)
        {
            this._projectModelFactory = projectModelFactory;
        }

        public IViewComponentResult Invoke(int? productThumbPictureSize)
        {
            var model = _projectModelFactory.PrepareTopMenuModel();
            return View(model);
        }
    }
}

Presentation/IQDashboard.Web/Controllers/AccountController.cs
using IQDashboard.Data.Repository;
using IQDashboard.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace IQDashboard.Web.Controllers
{
    public class AccountController : Controller
    {
        private readonly ILogger<AccountController> _logger;
        private readonly IIQP _repository;

        public AccountController(ILogger<AccountController> logger, IIQP repository)
        {
            _logger = logger;
            _repository = repository;
        }

        [HttpGet]
        public IActionResult Login()
        {

            if (this.User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _repository.ValidateUser(model.UserName, model.Password);

                if (result != null)
                {
                    if (Request.Query.Keys.Contains("ReturnUrl"))
                    {
                        return Redirect(Request.Query["ReturnUrl"]);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            ModelState.AddModelError("", "Failed To Login");
            return View();
        }
    }
}

Presentation/IQDashboard.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace IQDashboard.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Presentation/IQDashboard.Web/Controllers/ProjecthandbookController.cs
using IQDashboard.Core.Domain;
using IQDashboard.Service.Handbook;
using IQDashboard.Web.Factories;
using IQDashboard.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace IQDashboard.Web.Controllers
{
    public class ProjecthandbookController : Controller
    {
       // private readonly IIQModelFactory _projectModelFactory;

        private readonly IHandbookService _handbookService;

        public ProjecthandbookController(IHandbookService handbookService)
        {
            //this._projectModelFactory = projectModelFactory;
            this._handbookService=handbookService;
        }

        public IActionResult ProjectHandbook()
        {
            return View();
        }

        public IActionResult Handbook(string next)
        {
            return PartialView();
        }

        [HttpPost]
        public IActionResult Handbook(ProjectSummaryViewModel model)
        {
            if (ModelState.IsValid)
            {
                ProjectSummary summary = new ProjectSummary
                {
                    ClientName = model.ClientName,
                    ProjectName = model.ProjectName,
                    ProjectStartDate = model.ProjectStartDate,
                    ProjectEndDate = model.ProjectEndDate,
                    ActualStartDate = model.ActualStartDate,
                    ForecastedEndDate = model.ForecastedEndDate,
                    ProjectId = 1
                };

                _handbookService.InsertProjectSummary(summary);
            }
            else
            {
                ModelState.AddModelError("", "Failed To Save");
            }
            return RedirectToAction("Handbook");
        }

        public IActionResult Risk()
        {
            return PartialView();
        }
    }
}

Presentation/IQDashboard.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Presentation/IQDashboard.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Presentation/IQDashboard.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Internal Quality Dashboard";
}
@section Scripts{
    <script type="text/javascript">google.charts.load('current', { packages: ['corechart'] });</script>
    <script src="~/js/dashboard.js"></script>
}
<div class="app-title">
    <div>
        <h1 class="page-header">Dashboard</h1>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
           
            <div class="panel-body">
                <div class="col-md-6">
                    <div class="tile">
                        <div class="tile-title-w-btn">
                            <h3 class="tile-title">Financial Services</h3>
                        </div>
                        <div class="tile-body">
                            <div id="fs" class="embed-responsive-item"></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="tile">
                        <div class="tile-title-w-btn">
                            <h3 class="tile-title">Communication Engineering</h3>
                        </div>
                        <div class="tile-body">
                            <div id="ce" class="embed-responsive-item"></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="tile">
                        <div class="tile-title-w-btn">
                            <h3 class="tile-title">Life Science</h3>
                        </div>
                        <div class="tile-body">
                            <div id="ls" class="embed-responsive-item"></div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="tile">
                        <div class="tile-title-w-btn">
                            <h3 class="tile-title">Business Operations</h3>
                        </div>
                        <div class="tile-body">
                            <div id="bo" class="embed-responsive-item"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Presentation/IQDashboard.Web/Views/Projecthandbook/ProjectHandbook.cshtml
@{
    ViewData["Title"] = "ProjectHandbook";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Project Handbook</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    HandBook
                </div>
                <div class="panel-body">
                    <!-- Nav tabs -->
                    <ul class="nav nav-tabs" style="font-size:10px !important" id="myTab">
                        <li class="active">
                            <a href="#tabs-1" onclick="getContentTab(1,'Handbook')" data-toggle="tab">Project Summary</a>
                        </li>
                        <li>
                            <a href="#tabs-2" onclick="getContentTab(2,'Risk')" data-toggle="tab">Risk</a>
                        </li>
                        <li>
                            <a href="#tabs-3" onclick="getContentTab(3,'ongoingprojectrisk')" data-toggle="tab">Ongoing Project Risks</a>
                        </li>
                        <li>
                            <a href="#tabs-4" onclick="getContentTab(4,'dm')" data-toggle="tab">Delivery Methodology</a>
                        </li>
                        <li>
                            <a href="#tabs-5" onclick="getContentTab(5,'md')" data-toggle="tab">Milestones and Deliverables</a>
                        </li>
                        <li>
                            <a href="#tabs-6" onclick="getContentTab(6,'ts')" data-toggle="tab">Team Structure</a>
                        </li>
                        <li>
                            <a href="#tabs-7" onclick="getContentTab(7,'Governance')" data-toggle="tab">Governance</a>
                        </li>
                        <li>
                            <a href="#tabs-8" onclick="getContentTab(8,'km')" data-toggle="tab">KPIs and Metrics</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade active in" id="tabs-1">

                        </div>
                        <div class="tab-pane fade" id="tabs-2">
                        </div>
                        <div class="tab-pane fade" id="tabs-3">
                        </div>
                        <div class="tab-pane fade" id="tabs-4">
                        </div>
                        <div class="tab-pane fade" id="tabs-5">
                        </div>
                        <div class="tab-pane fade" id="tabs-6">
                        </div>
                        <div class="tab-pane fade" id="tabs-7">
                        </div>
                        <div class="tab-pane fade" id="tabs-8">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        getContentTab(1, 'Handbook');

    });
    function getContentTab(index, action) {
        var targetDiv = "#tabs-" + index;
        //var nexttargetDiv = "#tabs-" + (index + 1);
        $.ajax({
            type: "GET",
            url: "/Projecthandbook/" + action,
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (data) {
                $(targetDiv).html('');
                $(targetDiv).html(data);
                $(".datepicker").datepicker();
                var form = $('#summaryform')
                    .removeData("validator")
                    .removeData("unobtrusiveValidation");

                $.validator.unobtrusive.parse(form);
                //nextprevious();
            },
            error: function () {
                alert("Error occured!!")
            }
        });
    }

    function nextprevious() {
        $('.btnNext').click(function () {
            if (ViewData.ModelState.IsValid) {
                $('.nav-tabs > .active').next('li').find('a').trigger('click');
            }
            else { alert('false'); }
        });

        $('.btnPrevious').click(function () {
            $('.nav-tabs > .active').prev('li').find('a').trigger('click');
        });
    }

    $(document).ready(() => {
        let url = location.href.replace(/\/$/, "");

        if (location.hash) {
            const hash = url.split("#");
            $('#myTab a[href="#' + hash[1] + '"]').tab("show");
            url = location.href.replace(/\/#/, "#");
            history.replaceState(null, null, url);
            setTimeout(() => {
                $(window).scrollTop(0);
            }, 400);
        }

        $('a[data-toggle="tab"]').on("click", function () {
            let newUrl;
            const hash = $(this).attr("href");
            if (hash == "#tabs-1") {
                newUrl = url.split("#")[0];
            } else {
                newUrl = url.split("#")[0] + hash;
            }
            newUrl += "/";
            history.replaceState(null, null, newUrl);
        });
    });

</script>

Presentation/IQDashboard.Web/Views/Projecthandbook/handbook.cshtml
@model ProjectSummaryModel

<div class="col-md-12">
    <div class="tile">
        <h3 class="tile-title">Project Summary</h3>
        <div class="tile-body">
            <form id="summaryform" class="login-form" asp-action="Handbook" asp-controller="Projecthandbook" method="post">

                <div class="form-group col-md-3">
                    <label class="control-label">Client Name</label>
                    <input asp-for="ClientName" class="form-control" placeholder="Enter client name" autofocus>
                    <span asp-validation-for="ClientName" class="table-warning"></span>
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Project Name (as per SOW)</label>
                    @Html.TextBoxFor(m => m.ProjectName, new { @class = "form-control", @placeholder = "Enter project name" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Function</label>
                    @Html.TextBoxFor(m => m.Function, new { @class = "form-control", @placeholder = "Enter function" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">BU Head</label>
                    @Html.TextBoxFor(m => m.BUHead, new { @class = "form-control", @placeholder = "Enter BU head" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Delivery Head</label>
                    @Html.TextBoxFor(m => m.DeliveryHead, new { @class = "form-control", @placeholder = "Enter delivery head" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Account Manager</label>
                    @Html.TextBoxFor(m => m.AccountManager, new { @class = "form-control", @placeholder = "Enter account manager" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Project Manager</label>
                    @Html.TextBoxFor(m => m.ProjectManager, new { @class = "form-control", @placeholder = "Enter project manager" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Current SOW#</label>
                    @Html.TextBoxFor(m => m.CurrentSOW, new { @class = "form-control", @placeholder = "Enter current SOW" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Start Date (as per SOW)</label>
                    @Html.TextBoxFor(m => m.ProjectStartDate, new { @class = "form-control datepicker", @placeholder = "Enter project start date (as per SOW)" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">End Date (as per SOW)</label>
                    @Html.TextBoxFor(m => m.ProjectEndDate, new { @class = "form-control datepicker", @placeholder = "Enter project end date (as per SOW)" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Actual Start Date</label>
                    @Html.TextBoxFor(m => m.ActualStartDate, new { @class = "form-control datepicker", @placeholder = "Enter actual start" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Forecasted End Date</label>
                    @Html.TextBoxFor(m => m.ForecastedEndDate, new { @class = "form-control datepicker", @placeholder = "Enter forecasted end date" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Project Type</label>
                    @Html.TextBoxFor(m => m.ProjectType, new { @class = "form-control", @placeholder = "Enter project type" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Pricing Code</label>
                    @Html.TextBoxFor(m => m.PricingCode, new { @class = "form-control", @placeholder = "Enter pricing code" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Billing Type</label>
                    @Html.TextBoxFor(m => m.BillingType, new { @class = "form-control", @placeholder = "Enter billing type" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Project Summary</label>
                    @Html.TextAreaFor(m => m.ProjectSummary, new { @class = "form-control", @placeholder = "Enter project summary" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Project Success Criterias (inputs to KPI's)</label>
                    @Html.TextAreaFor(m => m.PSC, new { @class = "form-control", @placeholder = "Enter project success criterias" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Assumptions</label>
                    @Html.TextAreaFor(m => m.Assumptions, new { @class = "form-control", @placeholder = "Enter assumptions" })
                </div>
                <div class="form-group col-md-3">
                    <label class="control-label">Constraints</label>
                    @Html.TextAreaFor(m => m.Constraints, new { @class = "form-control", @placeholder = "Enter constraints" })
                </div>
                <div class="form-group col-md-12" style="text-align:right">
                    <button type="submit" class="btn btn-primary btnNext">Save and Next</button>
                </div>
            </form>
        </div>
    </div>
</div>

Presentation/IQDashboard.Web/Views/Shared/Components/Menu/Default.cshtml
@model TopMenuModel
@*<ul class="app-menu">
        <li><a class="app-menu__item active" href="/Home/Index"><i class="app-menu__icon fas fa-fw fa-tachometer-alt"></i><span class="app-menu__label">Dashboard</span></a></li>
        @foreach (var item in Model.Where(c => c.ParentId == 1))
        {
            <a class="app-menu__item" href="@item.NavigationUrl" data-toggle="treeview"><i class="app-menu__icon fa fa-laptop"></i><span class="app-menu__label">@item.NavName</span><i class="treeview-indicator fa fa-angle-right"></i></a>
            foreach (var product in Model.Where(c => c.NavId == item.ParentId))
            {
                <li class="treeview">
                    <ul class="treeview-menu">
                        <li><a class="treeview-item" href="@product.NavigationUrl"><i class="icon fa fa-square-o"></i> @product.NavName</a></li>
                    </ul>
                </li>
            }
        }
    </ul>*@
<ul class="sidebar-menu">
    <li class="treeview">
        <a href="#">
            <i class="glyphicon glyphicon-th-large"></i> <span>Dashboard</span>
        </a>
    </li>
    <li>
        <a href="#">
            <i class="fa fa-list-ul"></i> <span>Cases</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li>
                <a href="#">
                    <i class="fa fa-circle-o"></i> LS
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">


                    <li>
                        <a href="#">
                            <i class="fa fa-circle-o"></i> Client
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">

                            <li>
                                <a href="#">
                                    <i class="fa fa-circle-o"></i> Project
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li>
                                        <a asp-action="ProjectHandbook" asp-controller="Projecthandbook"><i class="fa fa-circle-o"></i> HandBook</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </li>
</ul>

Presentation/IQDashboard.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>

    <environment include="Development">
        <link href="~/css/style.css" rel="stylesheet" />
        <link href="~/css/skin.css" rel="stylesheet" />
        <link href="~/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/jquery-ui.css" rel="stylesheet" />
        <link href="~/css/jquery-ui.theme.css" rel="stylesheet" />
        <link href="~/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/css/ionicons.min.css" rel="stylesheet" />
        <script src="~/js/jquery.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js">
        </script>
    </environment>
    <environment exclude="Development">
        @*<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />*@
        <link href="~/css/main.css" rel="stylesheet" />
        <link href="~/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/css/all.min.css" rel="stylesheet" />
    </environment>
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- HEADER SECTION -->
        <header class="main-header">
            <nav class="navbar navbar-static-top">
                <a href="landing-screen.html" class="logo">
                    <span class="logo-lg"><img src="~/images/logo.png" width="30px" /></span>
                </a>
                <div class="navbar-custom-menu">
                    <div class="search-form">

                    </div>
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Username</a>
                            <ul class="dropdown-menu">
                                <li class="user-footer">
                                    <a href="#" class="btn btn-default">Sign out</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">
                @await Component.InvokeAsync("Menu")
            </section>
        </aside>
        <div class="content-wrapper">
            <section class="content open-navigation">
                @RenderBody()
            </section>
        </div>
        <div id="footer">
            <p>&copy;  INCEDO &nbsp;@DateTime.Now.Year &nbsp;</p>
        </div>
    </div>
    <environment include="Development">
        <script src="~/js/jquery-ui.js"></script>
        <script src="~/js/app.min.js"></script>
        <script src="~/js/common.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>*@
        <script src="~/js/jquery.min.js"></script>
        <script src="~/js/popper.min.js"></script>
        <script src="~/js/bootstrap.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Presentation/IQDashboard.Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/main_o.css" rel="stylesheet" />
    <link href="~/css/font-awesome.css" rel="stylesheet" />
</head>
<body>
    <section class="material-half-bg">
        <div class="cover"></div>
    </section>
    <section class="login-content">
        <div class="logo">
            <img height="30px" src="~/images/logo.png" />
        </div>
        @RenderBody()
    </section>

    <script src="~/js/jquery.min.js"></script>
    @RenderSection("Scripts", false)
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        // Login Page Flipbox control
        $('.login-content [data-toggle="flip"]').click(function () {
            $('.login-box').toggleClass('flipped');
            return false;
        });
    </script>
</body>
</html>

Presentation/IQDashboard.Web/Views/Shared/_projectSummary.cshtml
<div class="row">
    <div class="col-lg-12">
        <form class="form-horizontal form-label-left">
            <div class="form-group">
                <br>
                <label class="control-label col-md-3" for="first-name">
                    First Name <span class="required">*</span>
                </label>
                <div class="col-md-7">
                    <input type="text" id="first-name2" required="required" class="form-control col-md-7 col-xs-12">
                </div>
            </div>
        </form>
    </div>
    <button type="submit" class="btn btn-success pull-right">Submit Button</button>
</div>
<a class="btn btn-primary btnNext">Next</a>